# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nativedroid/protobuf/java_signatures.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='nativedroid/protobuf/java_signatures.proto',
  package='jawa_core',
  syntax='proto3',
  serialized_options=_b('\n\023org.argus.jawa.core'),
  serialized_pb=_b('\n*nativedroid/protobuf/java_signatures.proto\x12\tjawa_core\"C\n\x0bJavaPackage\x12\x0c\n\x04name\x18\x01 \x01(\t\x12&\n\x06parent\x18\x02 \x01(\x0b\x32\x16.jawa_core.JavaPackage\"\xa4\x01\n\rPrimitiveType\x12\x30\n\x04type\x18\x01 \x01(\x0e\x32\".jawa_core.PrimitiveType.Primitive\"a\n\tPrimitive\x12\x08\n\x04\x42YTE\x10\x00\x12\t\n\x05SHORT\x10\x01\x12\x07\n\x03INT\x10\x02\x12\t\n\x05\x46LOAT\x10\x03\x12\x0b\n\x07\x42OOLEAN\x10\x04\x12\x08\n\x04\x43HAR\x10\x05\x12\x08\n\x04LONG\x10\x06\x12\n\n\x06\x44OUBLE\x10\x07\"S\n\tClassType\x12\'\n\x07package\x18\x01 \x01(\x0b\x32\x16.jawa_core.JavaPackage\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07unknown\x18\x03 \x01(\x08\"\n\n\x08VoidType\"\x8a\x01\n\x08JavaType\x12\x32\n\x0eprimitive_type\x18\x01 \x01(\x0b\x32\x18.jawa_core.PrimitiveTypeH\x00\x12*\n\nclass_type\x18\x02 \x01(\x0b\x32\x14.jawa_core.ClassTypeH\x00\x12\x11\n\tdimension\x18\x03 \x01(\x05\x42\x0b\n\tbase_type\"\xa8\x01\n\x0bMethodProto\x12(\n\x0bparam_types\x18\x01 \x03(\x0b\x32\x13.jawa_core.JavaType\x12/\n\x10return_java_type\x18\x02 \x01(\x0b\x32\x13.jawa_core.JavaTypeH\x00\x12/\n\x10return_void_type\x18\x03 \x01(\x0b\x32\x13.jawa_core.VoidTypeH\x00\x42\r\n\x0breturn_type\"j\n\x0fMethodSignature\x12\"\n\x05owner\x18\x01 \x01(\x0b\x32\x13.jawa_core.JavaType\x12\x0c\n\x04name\x18\x02 \x01(\t\x12%\n\x05proto\x18\x03 \x01(\x0b\x32\x16.jawa_core.MethodProto\"k\n\x0e\x46ieldSignature\x12\"\n\x05owner\x18\x01 \x01(\x0b\x32\x13.jawa_core.JavaType\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\'\n\nfield_type\x18\x03 \x01(\x0b\x32\x13.jawa_core.JavaTypeB\x15\n\x13org.argus.jawa.coreb\x06proto3')
)



_PRIMITIVETYPE_PRIMITIVE = _descriptor.EnumDescriptor(
  name='Primitive',
  full_name='jawa_core.PrimitiveType.Primitive',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BYTE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SHORT', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INT', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FLOAT', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BOOLEAN', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CHAR', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LONG', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DOUBLE', index=7, number=7,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=194,
  serialized_end=291,
)
_sym_db.RegisterEnumDescriptor(_PRIMITIVETYPE_PRIMITIVE)


_JAVAPACKAGE = _descriptor.Descriptor(
  name='JavaPackage',
  full_name='jawa_core.JavaPackage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='jawa_core.JavaPackage.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parent', full_name='jawa_core.JavaPackage.parent', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=124,
)


_PRIMITIVETYPE = _descriptor.Descriptor(
  name='PrimitiveType',
  full_name='jawa_core.PrimitiveType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='jawa_core.PrimitiveType.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PRIMITIVETYPE_PRIMITIVE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=127,
  serialized_end=291,
)


_CLASSTYPE = _descriptor.Descriptor(
  name='ClassType',
  full_name='jawa_core.ClassType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='package', full_name='jawa_core.ClassType.package', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='jawa_core.ClassType.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unknown', full_name='jawa_core.ClassType.unknown', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=293,
  serialized_end=376,
)


_VOIDTYPE = _descriptor.Descriptor(
  name='VoidType',
  full_name='jawa_core.VoidType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=378,
  serialized_end=388,
)


_JAVATYPE = _descriptor.Descriptor(
  name='JavaType',
  full_name='jawa_core.JavaType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='primitive_type', full_name='jawa_core.JavaType.primitive_type', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='class_type', full_name='jawa_core.JavaType.class_type', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dimension', full_name='jawa_core.JavaType.dimension', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='base_type', full_name='jawa_core.JavaType.base_type',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=391,
  serialized_end=529,
)


_METHODPROTO = _descriptor.Descriptor(
  name='MethodProto',
  full_name='jawa_core.MethodProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='param_types', full_name='jawa_core.MethodProto.param_types', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='return_java_type', full_name='jawa_core.MethodProto.return_java_type', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='return_void_type', full_name='jawa_core.MethodProto.return_void_type', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='return_type', full_name='jawa_core.MethodProto.return_type',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=532,
  serialized_end=700,
)


_METHODSIGNATURE = _descriptor.Descriptor(
  name='MethodSignature',
  full_name='jawa_core.MethodSignature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='owner', full_name='jawa_core.MethodSignature.owner', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='jawa_core.MethodSignature.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='proto', full_name='jawa_core.MethodSignature.proto', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=702,
  serialized_end=808,
)


_FIELDSIGNATURE = _descriptor.Descriptor(
  name='FieldSignature',
  full_name='jawa_core.FieldSignature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='owner', full_name='jawa_core.FieldSignature.owner', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='jawa_core.FieldSignature.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='field_type', full_name='jawa_core.FieldSignature.field_type', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=810,
  serialized_end=917,
)

_JAVAPACKAGE.fields_by_name['parent'].message_type = _JAVAPACKAGE
_PRIMITIVETYPE.fields_by_name['type'].enum_type = _PRIMITIVETYPE_PRIMITIVE
_PRIMITIVETYPE_PRIMITIVE.containing_type = _PRIMITIVETYPE
_CLASSTYPE.fields_by_name['package'].message_type = _JAVAPACKAGE
_JAVATYPE.fields_by_name['primitive_type'].message_type = _PRIMITIVETYPE
_JAVATYPE.fields_by_name['class_type'].message_type = _CLASSTYPE
_JAVATYPE.oneofs_by_name['base_type'].fields.append(
  _JAVATYPE.fields_by_name['primitive_type'])
_JAVATYPE.fields_by_name['primitive_type'].containing_oneof = _JAVATYPE.oneofs_by_name['base_type']
_JAVATYPE.oneofs_by_name['base_type'].fields.append(
  _JAVATYPE.fields_by_name['class_type'])
_JAVATYPE.fields_by_name['class_type'].containing_oneof = _JAVATYPE.oneofs_by_name['base_type']
_METHODPROTO.fields_by_name['param_types'].message_type = _JAVATYPE
_METHODPROTO.fields_by_name['return_java_type'].message_type = _JAVATYPE
_METHODPROTO.fields_by_name['return_void_type'].message_type = _VOIDTYPE
_METHODPROTO.oneofs_by_name['return_type'].fields.append(
  _METHODPROTO.fields_by_name['return_java_type'])
_METHODPROTO.fields_by_name['return_java_type'].containing_oneof = _METHODPROTO.oneofs_by_name['return_type']
_METHODPROTO.oneofs_by_name['return_type'].fields.append(
  _METHODPROTO.fields_by_name['return_void_type'])
_METHODPROTO.fields_by_name['return_void_type'].containing_oneof = _METHODPROTO.oneofs_by_name['return_type']
_METHODSIGNATURE.fields_by_name['owner'].message_type = _JAVATYPE
_METHODSIGNATURE.fields_by_name['proto'].message_type = _METHODPROTO
_FIELDSIGNATURE.fields_by_name['owner'].message_type = _JAVATYPE
_FIELDSIGNATURE.fields_by_name['field_type'].message_type = _JAVATYPE
DESCRIPTOR.message_types_by_name['JavaPackage'] = _JAVAPACKAGE
DESCRIPTOR.message_types_by_name['PrimitiveType'] = _PRIMITIVETYPE
DESCRIPTOR.message_types_by_name['ClassType'] = _CLASSTYPE
DESCRIPTOR.message_types_by_name['VoidType'] = _VOIDTYPE
DESCRIPTOR.message_types_by_name['JavaType'] = _JAVATYPE
DESCRIPTOR.message_types_by_name['MethodProto'] = _METHODPROTO
DESCRIPTOR.message_types_by_name['MethodSignature'] = _METHODSIGNATURE
DESCRIPTOR.message_types_by_name['FieldSignature'] = _FIELDSIGNATURE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

JavaPackage = _reflection.GeneratedProtocolMessageType('JavaPackage', (_message.Message,), dict(
  DESCRIPTOR = _JAVAPACKAGE,
  __module__ = 'nativedroid.protobuf.java_signatures_pb2'
  # @@protoc_insertion_point(class_scope:jawa_core.JavaPackage)
  ))
_sym_db.RegisterMessage(JavaPackage)

PrimitiveType = _reflection.GeneratedProtocolMessageType('PrimitiveType', (_message.Message,), dict(
  DESCRIPTOR = _PRIMITIVETYPE,
  __module__ = 'nativedroid.protobuf.java_signatures_pb2'
  # @@protoc_insertion_point(class_scope:jawa_core.PrimitiveType)
  ))
_sym_db.RegisterMessage(PrimitiveType)

ClassType = _reflection.GeneratedProtocolMessageType('ClassType', (_message.Message,), dict(
  DESCRIPTOR = _CLASSTYPE,
  __module__ = 'nativedroid.protobuf.java_signatures_pb2'
  # @@protoc_insertion_point(class_scope:jawa_core.ClassType)
  ))
_sym_db.RegisterMessage(ClassType)

VoidType = _reflection.GeneratedProtocolMessageType('VoidType', (_message.Message,), dict(
  DESCRIPTOR = _VOIDTYPE,
  __module__ = 'nativedroid.protobuf.java_signatures_pb2'
  # @@protoc_insertion_point(class_scope:jawa_core.VoidType)
  ))
_sym_db.RegisterMessage(VoidType)

JavaType = _reflection.GeneratedProtocolMessageType('JavaType', (_message.Message,), dict(
  DESCRIPTOR = _JAVATYPE,
  __module__ = 'nativedroid.protobuf.java_signatures_pb2'
  # @@protoc_insertion_point(class_scope:jawa_core.JavaType)
  ))
_sym_db.RegisterMessage(JavaType)

MethodProto = _reflection.GeneratedProtocolMessageType('MethodProto', (_message.Message,), dict(
  DESCRIPTOR = _METHODPROTO,
  __module__ = 'nativedroid.protobuf.java_signatures_pb2'
  # @@protoc_insertion_point(class_scope:jawa_core.MethodProto)
  ))
_sym_db.RegisterMessage(MethodProto)

MethodSignature = _reflection.GeneratedProtocolMessageType('MethodSignature', (_message.Message,), dict(
  DESCRIPTOR = _METHODSIGNATURE,
  __module__ = 'nativedroid.protobuf.java_signatures_pb2'
  # @@protoc_insertion_point(class_scope:jawa_core.MethodSignature)
  ))
_sym_db.RegisterMessage(MethodSignature)

FieldSignature = _reflection.GeneratedProtocolMessageType('FieldSignature', (_message.Message,), dict(
  DESCRIPTOR = _FIELDSIGNATURE,
  __module__ = 'nativedroid.protobuf.java_signatures_pb2'
  # @@protoc_insertion_point(class_scope:jawa_core.FieldSignature)
  ))
_sym_db.RegisterMessage(FieldSignature)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
