# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from nativedroid.protobuf import jnsaf_grpc_pb2 as nativedroid_dot_protobuf_dot_jnsaf__grpc__pb2


class JNSafStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.LoadAPK = channel.stream_unary(
        '/jnsaf_server.JNSaf/LoadAPK',
        request_serializer=nativedroid_dot_protobuf_dot_jnsaf__grpc__pb2.LoadAPKRequest.SerializeToString,
        response_deserializer=nativedroid_dot_protobuf_dot_jnsaf__grpc__pb2.LoadAPKResponse.FromString,
        )
    self.TaintAnalysis = channel.unary_unary(
        '/jnsaf_server.JNSaf/TaintAnalysis',
        request_serializer=nativedroid_dot_protobuf_dot_jnsaf__grpc__pb2.TaintAnalysisRequest.SerializeToString,
        response_deserializer=nativedroid_dot_protobuf_dot_jnsaf__grpc__pb2.TaintAnalysisResponse.FromString,
        )
    self.GetSummary = channel.unary_unary(
        '/jnsaf_server.JNSaf/GetSummary',
        request_serializer=nativedroid_dot_protobuf_dot_jnsaf__grpc__pb2.GetSummaryRequest.SerializeToString,
        response_deserializer=nativedroid_dot_protobuf_dot_jnsaf__grpc__pb2.GetSummaryResponse.FromString,
        )
    self.RegisterICC = channel.unary_unary(
        '/jnsaf_server.JNSaf/RegisterICC',
        request_serializer=nativedroid_dot_protobuf_dot_jnsaf__grpc__pb2.RegisterICCRequest.SerializeToString,
        response_deserializer=nativedroid_dot_protobuf_dot_jnsaf__grpc__pb2.RegisterICCResponse.FromString,
        )
    self.RegisterTaint = channel.unary_unary(
        '/jnsaf_server.JNSaf/RegisterTaint',
        request_serializer=nativedroid_dot_protobuf_dot_jnsaf__grpc__pb2.RegisterTaintRequest.SerializeToString,
        response_deserializer=nativedroid_dot_protobuf_dot_jnsaf__grpc__pb2.RegisterTaintResponse.FromString,
        )


class JNSafServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def LoadAPK(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def TaintAnalysis(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetSummary(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RegisterICC(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RegisterTaint(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_JNSafServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'LoadAPK': grpc.stream_unary_rpc_method_handler(
          servicer.LoadAPK,
          request_deserializer=nativedroid_dot_protobuf_dot_jnsaf__grpc__pb2.LoadAPKRequest.FromString,
          response_serializer=nativedroid_dot_protobuf_dot_jnsaf__grpc__pb2.LoadAPKResponse.SerializeToString,
      ),
      'TaintAnalysis': grpc.unary_unary_rpc_method_handler(
          servicer.TaintAnalysis,
          request_deserializer=nativedroid_dot_protobuf_dot_jnsaf__grpc__pb2.TaintAnalysisRequest.FromString,
          response_serializer=nativedroid_dot_protobuf_dot_jnsaf__grpc__pb2.TaintAnalysisResponse.SerializeToString,
      ),
      'GetSummary': grpc.unary_unary_rpc_method_handler(
          servicer.GetSummary,
          request_deserializer=nativedroid_dot_protobuf_dot_jnsaf__grpc__pb2.GetSummaryRequest.FromString,
          response_serializer=nativedroid_dot_protobuf_dot_jnsaf__grpc__pb2.GetSummaryResponse.SerializeToString,
      ),
      'RegisterICC': grpc.unary_unary_rpc_method_handler(
          servicer.RegisterICC,
          request_deserializer=nativedroid_dot_protobuf_dot_jnsaf__grpc__pb2.RegisterICCRequest.FromString,
          response_serializer=nativedroid_dot_protobuf_dot_jnsaf__grpc__pb2.RegisterICCResponse.SerializeToString,
      ),
      'RegisterTaint': grpc.unary_unary_rpc_method_handler(
          servicer.RegisterTaint,
          request_deserializer=nativedroid_dot_protobuf_dot_jnsaf__grpc__pb2.RegisterTaintRequest.FromString,
          response_serializer=nativedroid_dot_protobuf_dot_jnsaf__grpc__pb2.RegisterTaintResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'jnsaf_server.JNSaf', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
