# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from nativedroid.protobuf import nativedroid_grpc_pb2 as nativedroid_dot_protobuf_dot_nativedroid__grpc__pb2


class NativeDroidStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GenSummary = channel.unary_unary(
        '/nativedroid_server.NativeDroid/GenSummary',
        request_serializer=nativedroid_dot_protobuf_dot_nativedroid__grpc__pb2.GenSummaryRequest.SerializeToString,
        response_deserializer=nativedroid_dot_protobuf_dot_nativedroid__grpc__pb2.GenSummaryResponse.FromString,
        )
    self.GetDynamicRegisterMap = channel.unary_unary(
        '/nativedroid_server.NativeDroid/GetDynamicRegisterMap',
        request_serializer=nativedroid_dot_protobuf_dot_nativedroid__grpc__pb2.GetDynamicRegisterMapRequest.SerializeToString,
        response_deserializer=nativedroid_dot_protobuf_dot_nativedroid__grpc__pb2.GetDynamicRegisterMapResponse.FromString,
        )
    self.HasSymbol = channel.unary_unary(
        '/nativedroid_server.NativeDroid/HasSymbol',
        request_serializer=nativedroid_dot_protobuf_dot_nativedroid__grpc__pb2.HasSymbolRequest.SerializeToString,
        response_deserializer=nativedroid_dot_protobuf_dot_nativedroid__grpc__pb2.HasSymbolResponse.FromString,
        )
    self.AnalyseNativeActivity = channel.unary_unary(
        '/nativedroid_server.NativeDroid/AnalyseNativeActivity',
        request_serializer=nativedroid_dot_protobuf_dot_nativedroid__grpc__pb2.AnalyseNativeActivityRequest.SerializeToString,
        response_deserializer=nativedroid_dot_protobuf_dot_nativedroid__grpc__pb2.AnalyseNativeActivityResponse.FromString,
        )
    self.LoadBinary = channel.stream_unary(
        '/nativedroid_server.NativeDroid/LoadBinary',
        request_serializer=nativedroid_dot_protobuf_dot_nativedroid__grpc__pb2.LoadBinaryRequest.SerializeToString,
        response_deserializer=nativedroid_dot_protobuf_dot_nativedroid__grpc__pb2.LoadBinaryResponse.FromString,
        )


class NativeDroidServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GenSummary(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetDynamicRegisterMap(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def HasSymbol(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AnalyseNativeActivity(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def LoadBinary(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_NativeDroidServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GenSummary': grpc.unary_unary_rpc_method_handler(
          servicer.GenSummary,
          request_deserializer=nativedroid_dot_protobuf_dot_nativedroid__grpc__pb2.GenSummaryRequest.FromString,
          response_serializer=nativedroid_dot_protobuf_dot_nativedroid__grpc__pb2.GenSummaryResponse.SerializeToString,
      ),
      'GetDynamicRegisterMap': grpc.unary_unary_rpc_method_handler(
          servicer.GetDynamicRegisterMap,
          request_deserializer=nativedroid_dot_protobuf_dot_nativedroid__grpc__pb2.GetDynamicRegisterMapRequest.FromString,
          response_serializer=nativedroid_dot_protobuf_dot_nativedroid__grpc__pb2.GetDynamicRegisterMapResponse.SerializeToString,
      ),
      'HasSymbol': grpc.unary_unary_rpc_method_handler(
          servicer.HasSymbol,
          request_deserializer=nativedroid_dot_protobuf_dot_nativedroid__grpc__pb2.HasSymbolRequest.FromString,
          response_serializer=nativedroid_dot_protobuf_dot_nativedroid__grpc__pb2.HasSymbolResponse.SerializeToString,
      ),
      'AnalyseNativeActivity': grpc.unary_unary_rpc_method_handler(
          servicer.AnalyseNativeActivity,
          request_deserializer=nativedroid_dot_protobuf_dot_nativedroid__grpc__pb2.AnalyseNativeActivityRequest.FromString,
          response_serializer=nativedroid_dot_protobuf_dot_nativedroid__grpc__pb2.AnalyseNativeActivityResponse.SerializeToString,
      ),
      'LoadBinary': grpc.stream_unary_rpc_method_handler(
          servicer.LoadBinary,
          request_deserializer=nativedroid_dot_protobuf_dot_nativedroid__grpc__pb2.LoadBinaryRequest.FromString,
          response_serializer=nativedroid_dot_protobuf_dot_nativedroid__grpc__pb2.LoadBinaryResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'nativedroid_server.NativeDroid', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
